
markdown: redcarpet
permalink: /blog/:year/:month/:day/:categories/:title/

paginate: 3
paginate_path: "/blog/page:num/"

name: Jonas Webers Blog
description: cat /dev/mind
url: https://jonasw.de/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
